### ISSUE TITLE
Error when using fairseq models

### ISSUE THREAD

**Issue by reishikin** [bnsantoso/sub-to-audio#5]
**Hello, when trying to use fairseq model for Vietnamese, I encountered this error. I have no problem running the default model in English**

```
Traceback (most recent call last):
  File "subtoaudio_vie.py", line 2, in <module>
    sub = SubToAudio(model_path="G_100000.pth" , config_path="config.json")
  File "C:\Users\707spacestation\.conda\envs\vitstts\lib\site-packages\subtoaudio\subtoaudio.py", line 33, in __init__
    self.apitts = TTS(model_path=model_path,
  File "C:\Users\707spacestation\AppData\Roaming\Python\Python38\site-packages\TTS\api.py", line 294, in __init__
    self.load_tts_model_by_path(
  File "C:\Users\707spacestation\AppData\Roaming\Python\Python38\site-packages\TTS\api.py", line 417, in load_tts_model_by_path
    self.synthesizer = Synthesizer(
  File "C:\Users\707spacestation\AppData\Roaming\Python\Python38\site-packages\TTS\utils\synthesizer.py", line 91, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "C:\Users\707spacestation\AppData\Roaming\Python\Python38\site-packages\TTS\utils\synthesizer.py", line 181, in _load_tts
    self.tts_config = load_config(tts_config_path)
  File "C:\Users\707spacestation\AppData\Roaming\Python\Python38\site-packages\TTS\config\__init__.py", line 93, in load_config
    model_name = _process_model_name(config_dict)
  File "C:\Users\707spacestation\AppData\Roaming\Python\Python38\site-packages\TTS\config\__init__.py", line 61, in _process_model_name
    model_name = model_name.replace("_generator", "").replace("_discriminator", "")
AttributeError: 'dict' object has no attribute 'replace'
```

**This is my command:**

```
from subtoaudio import SubToAudio
sub = SubToAudio(model_path="G_100000.pth" , config_path="config.json")
subtitle = sub.subtitle("01.vi.srt")
sub.convert_to_audio(data=subtitle, tempo_mode="all", tempo_speed=1.3, lang="vie", output_path="01.vi.wav", save_temp=True,)

```
Thanks for your help!

**Comment by bnsantoso** [comment]
if you want use fairseq vietnam model : `sub = SubToAudio(language='vie') `. 

```python
sub = SubToAudio(languages='vie') 
subtitle = sub.subtitle("01.vi.srt")
sub.convert_to_audio(data=subtitle, tempo_mode="all", tempo_speed=1.3, output_path="01.vi.wav", save_temp=True,)

```
there is no need to pass `languages` argument on `self.convert_to_audio()` func. fairseq model only have 1 speaker and 1 languages.  and i notice that you give wrong argument `lang="vie"`, instead `languages="vie"`.

arg `languages` in `SubToAudio()` and `self.convert_to_audio()` have different purpose.  `SubToAudio(languages=<iso-code>)` is for initialze and downloading model.  `self.convert_to_audio(languages="fr-fr")` is for specify the languages within model that have multiple languages.


if you have your own model and config `sub = SubToAudio(model_path="G_100000.pth" , config_path="config.json")`, make sure it is correct model and corect config and correct path. isolate class instance to test or you can directly test your model from TTS api to check wether is perfeclty fine and can load. 

maybe you have similiar issue like this, the model and config.json is not suported, wrong or does not match with model :
[AttributeError: 'dict' object has no attribute 'replace'](https://github.com/coqui-ai/TTS/discussions/541)


if the model have multiple speaker and languages you can check them `print(sub.apitts.languages)` and `print(sub.apitts.speakers)`.

```python
from subtoaudio import SubToAudio
sub = SubToAudio(model_path="G_100000.pth" , config_path="config.json")
print(sub.apitts.languages) #print list of language on model
print(sub.apitts.speakers) #print list of speakers
```
